image: keymetrics/pm2:6

stages:
  - deploy

deploy_prod:
  stage: deploy
    script:
    - echo "====== Deploy to production server ======"
    - whoami
    - sudo apt-get update && sudo apt-get upgrade
    - sudo apt-get install git openssh-client bash
    # Install ssh-agent if not already installed, it is required by Docker.
    # (change apt-get to yum if you use a CentOS-based image)
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    # Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)
    # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # Deploy
    - echo "Setup tagget server directories"
    - pm2 deploy ecosystem.json production setup 2>&1 || true
    - echo "make deploy"
    - pm2 deploy ecosystem.json production
  environment:
    name: deploying
  only:
    - master
