image: keymetrics/pm2:6
services:
  - postgres:latest

variables:
  POSTGRES_DB: 'sample-nest'
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'supersecret'

stages:
  - deploy

deploy_prod:
  stage: deploy
  script:
    - echo "====== Deploy to production server ======"
    - chmod 400 bin/id_rsa.pem
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - sudo apt-get update && sudo apt-get upgrade
    - sudo apt-get install git openssh-client bash
    # Deploy
    - echo "Setup tagget server directories"
    - pm2 deploy ecosystem.json production setup 2>&1 || true
    - echo "make deploy"
    - pm2 deploy ecosystem.json production
  environment:
    name: deploying
  only:
    - master
