version: '3'

services:
  nest-api:
    build: .
    container_name: nest-api
    environment:
      - DB_HOST=postgres
    volumes:
      - .:/home/node/nestapi
      - /home/node/nestapi/node_modules
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    command: yarn start:dev
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  migrations:
    build: .
    command: yarn migration:run
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
